MODEL:
  TYPE: vssm
  NAME: vssm_tiny
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: "./code/pretrained_ckpt/vmamba_tiny_e292.pth"
  VSSM:
    IN_CHANS: 3         # <--- 加上这一行，明确告诉网络是3通道
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 2, 2 ]